inputDebounceDelayMs: 300
openers: []
colors:
  filePathText: "#9E40A1"
  highlightedText: "#FF0000"
  normalText: "#FFFFFF"
  selectedBackground: "#000000"
  focusedBorder: "#00FF00"
  highlightedBorder: "#CCC90A"
  unfocusedBorder: "#FFFFFF"
  popupBackgroundColor: "#000000"
  popupOverlayColor: "#000000C0"
  fileLineNumber: "#00FF00"
  defaultText: "#FFFFFF"
  truncationText: "#0000FF"
  errorBorder: "#FF0000"
markSymbol: "○"
selectionSymbol: ">"
layout:
  borderType: rounded
