name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run typecheck
      - run: bun run lint
      - run: bun run build

      - name: Create tar.gz archive
        run: tar -czf kondor.tar.gz -C dist .

      - name: Update CHANGELOG.md
        uses: orhun/git-cliff-action@v4
        with:
          args: -o CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}
          OUTPUT: CHANGELOG.md

      - name: Commit CHANGELOG.md
        run: |
          git checkout main
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git diff --cached --quiet && exit 0
          git commit -m "chore(release): prepare for ${{ github.ref_name }}"
          git push

      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --latest --strip header
        env:
          GITHUB_REPO: ${{ github.repository }}

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: kondor.tar.gz
          body: ${{ steps.git-cliff.outputs.content }}
          generate_release_notes: false

  update-homebrew:
    name: Update Homebrew Formula
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create and update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v4.1
        with:
          formula-name: kondor
          formula-path: Formula/kondor.rb
          homebrew-tap: ${{ github.repository_owner }}/homebrew-zapfhahn
          base-branch: main
          download-url: https://github.com/${{ github.repository }}/releases/download/v${{ steps.extract_version.outputs.VERSION }}/kondor.tar.gz
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
